# Generated by Django to resolve the duplicated user migration branches.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_options_alter_user_managers_and_more"),
        ("users", "0004_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = []
