# Generated by Django 5.2.16 on 2026-08-13 10:05, hand-extended with a data backfill.

import django.db.models.deletion
from django.db import migrations, models


def create_default_org_and_backfill(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    User = apps.get_model("users", "User")

    default_org, _ = Organization.objects.get_or_create(
        slug="default", defaults={"name": "Default Organization"},
    )
    User.objects.filter(organization__isnull=True).update(organization=default_org)


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('users', '0005_merge_20260812_000000'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The partner organization this user belongs to. Data is scoped to this boundary.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RunPython(create_default_org_and_backfill, migrations.RunPython.noop),
    ]
