# Generated by Django 6.0.5 on 2026-08-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_0007_alter_user_id_0008_emailotp_login_purpose'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='users_email_user_id_e2d0fe_idx',
            old_name='users_email_user_id_9d8614_idx',
        ),
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='users_email_expires_63503d_idx',
            old_name='users_email_expires_8d6581_idx',
        ),
    ]
