# Generated by Django 6.0.5 on 2026-05-21 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('detect_and_extract', 'Detect & Extract'), ('reconcile', 'Reconcile'), ('summarise_batch', 'Summarise Batch'), ('flag_anomalies', 'Flag Anomalies'), ('explain_variance', 'Explain Variance'), ('classify_lines', 'Classify Line Items'), ('generate_report', 'Generate Report'), ('custom', 'Custom Prompt')], max_length=30)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='queued', max_length=10)),
                ('user_intent', models.TextField(blank=True, help_text="Natural-language description of what the user wants, e.g. 'Extract all receipts and flag any with taxes above 10%'.")),
                ('system_prompt', models.TextField(blank=True)),
                ('user_prompt', models.TextField(help_text='The assembled prompt sent to the LLM (may include extracted file text).')),
                ('raw_response', models.TextField(blank=True)),
                ('structured_output', models.JSONField(blank=True, help_text='Final parsed result — anomalies list, summary dict, report metadata, etc.', null=True)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to='uploads.uploadbatch')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_jobs', to=settings.AUTH_USER_MODEL)),
                ('target_file', models.ForeignKey(blank=True, help_text='If set, this job focuses on one file; otherwise the whole batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_jobs', to='uploads.uploadedfile')),
            ],
            options={
                'verbose_name': 'AI Analysis Job',
                'verbose_name_plural': 'AI Analysis Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('anomaly', 'Anomaly'), ('variance_explanation', 'Variance Explanation'), ('summary_point', 'Summary Point'), ('classification', 'Classification'), ('recommendation', 'Recommendation')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('reference_key', models.CharField(blank=True, help_text='The CU invoice number, ACON item number, or phone number this insight relates to.', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField()),
                ('is_actioned', models.BooleanField(default=False)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actioned_insights', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='ai_engine.aianalysisjob')),
            ],
            options={
                'verbose_name': 'AI Insight',
                'verbose_name_plural': 'AI Insights',
                'ordering': ['-severity', 'created_at'],
            },
        ),
    ]
