# Generated by Django 6.0.5 on 2026-05-21 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsight',
            name='source_tool_call',
            field=models.ForeignKey(blank=True, help_text='The tool call that produced this insight, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insights', to='tools.toolcall'),
        ),
    ]
