# Generated by Django 5.2.16 on 2026-08-13 10:13, hand-extended with a data backfill.

import django.db.models.deletion
from django.db import migrations, models


def backfill_job_organization(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    AIAnalysisJob = apps.get_model("ai_engine", "AIAnalysisJob")

    default_org, _ = Organization.objects.get_or_create(
        slug="default", defaults={"name": "Default Organization"},
    )
    for job in AIAnalysisJob.objects.filter(organization__isnull=True).select_related("requested_by", "batch"):
        if job.requested_by_id and job.requested_by.organization_id:
            job.organization = job.requested_by.organization
        elif job.batch_id and job.batch.organization_id:
            job.organization = job.batch.organization
        else:
            job.organization = default_org
        job.save(update_fields=["organization"])


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_aiinsight_source_tool_call'),
        ('organizations', '0001_initial'),
        ('uploads', '0004_uploadbatch_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysisjob',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.organization'),
        ),
        migrations.RunPython(backfill_job_organization, migrations.RunPython.noop),
    ]
