# Generated by Django 6.0.5 on 2026-05-27 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('reconciliation', 'Reconciliation'), ('billing', 'Billing'), ('analytics', 'Analytics'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('generating', 'Generating'), ('error', 'Error')], default='generating', max_length=15)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
