# Generated by Django 5.2.16 on 2026-08-13 10:15, hand-extended with a data backfill.

import django.db.models.deletion
from django.db import migrations, models


def backfill_report_organization(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    Report = apps.get_model("analytics", "Report")

    default_org, _ = Organization.objects.get_or_create(
        slug="default", defaults={"name": "Default Organization"},
    )
    for report in Report.objects.filter(organization__isnull=True).select_related("requested_by"):
        report.organization = (
            report.requested_by.organization if report.requested_by_id and report.requested_by.organization_id
            else default_org
        )
        report.save(update_fields=["organization"])


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('organizations', '0001_initial'),
        ('users', '0006_organization_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.organization'),
        ),
        migrations.RunPython(backfill_report_organization, migrations.RunPython.noop),
    ]
