# chat/models.py
from django.db import models
from django.conf import settings


class ChatConversation(models.Model):
    """
    A conversation session between a user and the AI assistant.

    Conversations are the top-level container.  Each one belongs to one
    user and holds an ordered list of messages.  The assistant reads the
    last N messages as context on every turn.
    """
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="chat_conversations",
    )
    title = models.CharField(max_length=200, blank=True, default="Untitled Conversation")
    is_active = models.BooleanField(default=True)

    # Optional: pin the conversation to a batch so every message in it
    # has context about which files were uploaded
    related_batch = models.ForeignKey(
        "uploads.UploadBatch",
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name="conversations",
        help_text="Batch whose files provide context for this conversation.",
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-updated_at"]
        verbose_name = "Chat Conversation"
        verbose_name_plural = "Chat Conversations"

    def __str__(self) -> str:
        return f"{self.user.username} — {self.title}"


class ChatMessage(models.Model):
    """
    A single turn in a conversation.

    role = "user"      — typed by the human
    role = "assistant" — generated by the AI (may reference an AIAnalysisJob)
    role = "system"    — injected context (not shown in UI)
    """
    ROLE_CHOICES = [
        ("user",      "User"),
        ("assistant", "Assistant"),
        ("system",    "System"),
    ]

    conversation = models.ForeignKey(
        ChatConversation,
        on_delete=models.CASCADE,
        related_name="messages",
    )
    role    = models.CharField(max_length=10, choices=ROLE_CHOICES)
    content = models.TextField()

    # If this assistant message triggered an AI job, link it here
    # so the UI can show job status, insights, and output files inline
    ai_job = models.OneToOneField(
        "ai_engine.AIAnalysisJob",
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name="chat_message",
        help_text="AI job that was created to fulfil this message, if any.",
    )

    # Workflow selected by the user when sending this message
    applied_workflow = models.ForeignKey(
        "Workflow",
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name="messages",
    )

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_at"]
        verbose_name = "Chat Message"
        verbose_name_plural = "Chat Messages"

    def __str__(self) -> str:
        preview = self.content[:60].replace("\n", " ")
        return f"[{self.role}] {preview}"


class ChatMessageAttachment(models.Model):
    """
    A file attached to a ChatMessage.

    user_upload      — file the user dragged into the chat
    assistant_output — file the AI produced (xlsx, pdf report, etc.)

    When a user uploads a file, the service layer also creates an
    UploadedFile record (in the uploads app) so the AI engine can
    process it.  The FK below links the two records.
    """
    ATTACHMENT_TYPE_CHOICES = [
        ("user_upload",      "User Upload"),
        ("assistant_output", "Assistant Output"),
    ]

    message = models.ForeignKey(
        ChatMessage,
        on_delete=models.CASCADE,
        related_name="attachments",
    )
    file            = models.FileField(upload_to="chat/attachments/%Y/%m/")
    filename        = models.CharField(max_length=255)
    file_type       = models.CharField(max_length=20, blank=True)   # extension, e.g. "xlsx"
    attachment_type = models.CharField(max_length=20, choices=ATTACHMENT_TYPE_CHOICES)
    file_size_bytes = models.PositiveBigIntegerField(null=True, blank=True)

    # Cross-reference to the uploads app record (set for user_upload type)
    uploaded_file = models.OneToOneField(
        "uploads.UploadedFile",
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name="chat_attachment",
        help_text="Corresponding UploadedFile record in the uploads pipeline.",
    )

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_at"]
        verbose_name = "Chat Message Attachment"
        verbose_name_plural = "Chat Message Attachments"

    def __str__(self) -> str:
        return f"{self.filename} ({self.attachment_type})"


class Workflow(models.Model):
    """
    A named processing intent the user can select from the sidebar.

    Each workflow maps to a set of tool names the AI engine should
    prefer when handling a message.  The AI still decides exactly which
    tools to call — the workflow just scopes the available tool set and
    provides a focused system-prompt prefix.

    steps contains the ordered list of tool names, e.g.:
        ["detect_file_type", "extract_ura_receipts", "flag_anomalies", "generate_report"]
    """
    WORKFLOW_TYPE_CHOICES = [
        ("ura_processing",      "URA Fiscal Receipt Processing"),
        ("safaricom_processing","Safaricom Bill Processing"),
        ("acon_processing",     "ACON Sales Invoice Processing"),
        ("reconciliation",      "Reconciliation & Variance Detection"),
        ("classification",      "Line Item Classification"),
        ("report_generation",   "Report Generation"),
        ("custom",              "Custom Workflow"),
    ]

    name          = models.CharField(max_length=150)
    description   = models.TextField(blank=True)
    workflow_type = models.CharField(max_length=30, choices=WORKFLOW_TYPE_CHOICES)

    # Ordered list of tool names (must match ToolDefinition.name values)
    steps = models.JSONField(
        default=list,
        help_text=(
            "Ordered list of ToolDefinition.name values the AI should use, "
            "e.g. ['detect_file_type', 'extract_ura_receipts', 'generate_report']."
        ),
    )

    # System-prompt prefix injected when this workflow is active
    system_prompt_prefix = models.TextField(
        blank=True,
        help_text=(
            "Extra instruction prepended to the system prompt when this "
            "workflow is selected, e.g. 'Focus on URA fiscal receipts only.'."
        ),
    )

    enabled    = models.BooleanField(default=True)
    is_default = models.BooleanField(
        default=False,
        help_text="Show in the sidebar by default without the user needing to search.",
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["workflow_type", "name"]
        verbose_name = "Workflow"
        verbose_name_plural = "Workflows"

    def __str__(self) -> str:
        return f"{self.name} ({self.get_workflow_type_display()})"