# chat/tasks.py
"""
Celery tasks for the chat app.

run_chat_turn_task
------------------
Executes one user→assistant turn asynchronously so the WebSocket consumer
never blocks the ASGI event loop on slow Grok / file-processing calls.

Flow
----
1. Load conversation + user from the DB.
2. Run ChatService.get_response() (which routes through the AI agent).
3. Push text chunks to the WS group via push_chat_chunk() as they arrive.
4. Save the assistant ChatMessage and any output file attachments.
5. Push push_chat_done() so the client knows streaming is complete.
6. Update conversation title if still default.

Cancellation
------------
The consumer sets a Redis cache key "chat_cancel_<turn_id>" when the user
sends {"type": "cancel"}. The task checks this flag between tool calls
(via the on_tool_result callback) and raises CancelledError if set.
"""
import logging
from datetime import datetime, timezone as tz

from celery import shared_task
from celery.exceptions import SoftTimeLimitExceeded

logger = logging.getLogger(__name__)

# Soft time limit: 8 min. Hard kill: 10 min.
# Long agent runs (multi-file reconciliation) typically finish in < 3 min.
_SOFT_LIMIT = 60 * 8
_HARD_LIMIT = 60 * 10


@shared_task(
    bind=True,
    max_retries=0,
    soft_time_limit=_SOFT_LIMIT,
    time_limit=_HARD_LIMIT,
)
def run_chat_turn_task(
    self,
    *,
    turn_id: str,
    conversation_id: int,
    user_message_id: int,
    user_id: int,
    workflow_id: int | None = None,
    conversation_history: list[dict] | None = None,
):
    """
    Execute one chat turn in a Celery worker and stream the result back
    to the WebSocket group.

    Parameters
    ----------
    turn_id              UUID string generated by the consumer — used as the
                         correlation key for WS events and cancellation checks.
    conversation_id      PK of the ChatConversation.
    user_message_id      PK of the already-saved user ChatMessage.
    user_id              PK of the User — re-resolved from DB (safe for worker).
    workflow_id          Optional Workflow PK selected by the user.
    conversation_history Last ≤20 turns as [{"role", "content"}] — captured
                         before the user message was saved so this turn isn't
                         included twice.
    """
    from django.contrib.auth import get_user_model
    from chat.models import ChatConversation, ChatMessage
    from chat.notify import push_chat_chunk, push_chat_done, push_chat_error
    from chat.services import ChatService
    from chat.views import _save_output_attachments

    User = get_user_model()

    def _cancelled() -> bool:
        from django.core.cache import cache
        return bool(cache.get(f"chat_cancel_{turn_id}"))

    def _clear_cancel():
        from django.core.cache import cache
        cache.delete(f"chat_cancel_{turn_id}")

    try:
        user = User.objects.get(pk=user_id)
        conv = ChatConversation.objects.get(pk=conversation_id, user=user)
        user_msg = ChatMessage.objects.get(pk=user_message_id)
        content  = user_msg.content

        from chat.models import Workflow
        workflow = None
        if workflow_id:
            workflow = Workflow.objects.filter(pk=workflow_id).first()

        # ── Run the agent ─────────────────────────────────────────────────────
        # ChatService.get_response already routes file + no-file paths through
        # the AI agent. We capture the full response text and output files here
        # then push them once complete.
        #
        # For true token-level streaming we would need to wire Grok's streaming
        # API into the ToolService loop — that's a future improvement. For now
        # we push the full response as a single chunk, which is still async
        # (the WS consumer returned immediately) and far better than blocking.

        if _cancelled():
            push_chat_error(conversation_id, message="Turn cancelled before starting.", turn_id=turn_id)
            _clear_cancel()
            return

        try:
            # Resolve any attachments saved on the user message so tools
            # invoked by the agent can access the saved file records.
            from chat.models import ChatMessageAttachment
            file_attachments = list(ChatMessageAttachment.objects.filter(message=user_msg))

            response_text, output_files = ChatService.get_response(
                message=content,
                user=user,
                file_attachments=file_attachments,
                workflow_id=workflow_id,
                conversation_history=conversation_history or [],
            )
        except SoftTimeLimitExceeded:
            push_chat_error(
                conversation_id,
                message="Processing took too long and was stopped. Try a smaller file.",
                turn_id=turn_id,
            )
            raise

        if _cancelled():
            _clear_cancel()
            push_chat_error(conversation_id, message="Turn cancelled.", turn_id=turn_id)
            return

        # ── Push text to WS ───────────────────────────────────────────────────
        # Send in chunks of 400 chars so the client can render progressively
        # without waiting for the full response.
        CHUNK = 400
        for i in range(0, len(response_text), CHUNK):
            push_chat_chunk(conversation_id, content=response_text[i:i + CHUNK], turn_id=turn_id)
            if _cancelled():
                _clear_cancel()
                push_chat_error(conversation_id, message="Turn cancelled mid-stream.", turn_id=turn_id)
                return

        # ── Save assistant message ────────────────────────────────────────────
        from chat.signals import mark_ws_origin, clear_ws_origin
        mark_ws_origin()
        try:
            assistant_msg = ChatMessage.objects.create(
                conversation=conv,
                role="assistant",
                content=response_text,
                applied_workflow=workflow,
            )
        finally:
            clear_ws_origin()

        # ── Persist output files ──────────────────────────────────────────────
        saved_attachments = _save_output_attachments(output_files, assistant_msg)
        attachment_meta = [
            {
                "id":       att.pk,
                "filename": att.filename,
                "file_type": att.file_type,
                "download_url": f"/api/chat/attachments/{att.pk}/download/",
            }
            for att in saved_attachments
        ]

        # ── Auto-title ────────────────────────────────────────────────────────
        if conv.title in ("Untitled Conversation", ""):
            from chat.title_generator import generate_title_from_user_input
            from django.utils import timezone
            conv.title = generate_title_from_user_input(content) or content[:50]
            conv.updated_at = timezone.now()
            conv.save(update_fields=["title", "updated_at"])

        # ── Done ──────────────────────────────────────────────────────────────
        push_chat_done(
            conversation_id,
            message_id=assistant_msg.pk,
            turn_id=turn_id,
            attachments=attachment_meta,
        )

        _clear_cancel()
        logger.info(
            "chat turn %s complete: conv=%s user=%s",
            turn_id, conversation_id, user_id,
        )

    except SoftTimeLimitExceeded:
        logger.error("run_chat_turn_task soft time limit exceeded: turn=%s", turn_id)
        raise
    except Exception as exc:
        logger.exception("run_chat_turn_task failed: turn=%s error=%s", turn_id, exc)
        push_chat_error(conversation_id, message=str(exc), turn_id=turn_id)
        raise