# chat/tasks.py
"""
Celery tasks for the chat app.

run_chat_turn_task
------------------
Executes one user→assistant turn in a Celery worker (the dedicated "chat"
queue — see config/celery.py) so neither the WebSocket consumer nor a REST
send view's request thread blocks the ASGI event loop, and so the turn runs
with the worker's own generous time limits (8 min soft) instead of nginx's
much shorter proxy_read_timeout on the HTTP path. REST views dispatch this
same task and block briefly on the AsyncResult (see
chat/views.py:_run_turn_via_worker) rather than running the agent inline.

Flow
----
1. Load conversation + user from the DB.
2. Run ChatService.get_response() (which routes through the AI agent).
3. Push text chunks to the WS group via push_chat_chunk() as they arrive.
4. Save the assistant ChatMessage and any output file attachments.
5. Push push_chat_done() so the client knows streaming is complete.
6. Update conversation title if still default.

Cancellation
------------
The consumer sets a Redis cache key "chat_cancel_<turn_id>" when the user
sends {"type": "cancel"}. The task checks this flag between tool calls
(via the on_tool_result callback) and raises CancelledError if set.

Reliability
-----------
CELERY_TASK_ACKS_LATE (global, settings.py) means Celery only removes this
task from the queue after it finishes — so a worker that crashes mid-turn
gets its task redelivered to another worker instead of losing it silently.
That guarantee is only useful if redelivery can't double-post an assistant
reply, so the task takes out a short-lived Redis lock keyed by turn_id before
doing any work; a duplicate delivery for the same turn is a no-op.

Transient failures (Grok rate limits / connection errors) are retried a
bounded number of times with backoff. Anything else — a real bug, a bad
request — still surfaces immediately as a user-facing error via
push_chat_error rather than retrying forever.
"""
import logging
from datetime import datetime, timezone as tz

from celery import shared_task
from celery.exceptions import SoftTimeLimitExceeded

logger = logging.getLogger(__name__)

# Soft time limit: 8 min. Hard kill: 10 min.
# Long agent runs (multi-file reconciliation) typically finish in < 3 min.
_SOFT_LIMIT = 60 * 8
_HARD_LIMIT = 60 * 10


@shared_task(
    bind=True,
    max_retries=2,
    acks_late=True,
    soft_time_limit=_SOFT_LIMIT,
    time_limit=_HARD_LIMIT,
)
def run_chat_turn_task(
    self,
    *,
    turn_id: str,
    conversation_id: int,
    user_message_id: int,
    user_id: int,
    workflow_id: int | None = None,
    conversation_history: list[dict] | None = None,
):
    """
    Execute one chat turn in a Celery worker and stream the result back
    to the WebSocket group.

    Parameters
    ----------
    turn_id              UUID string generated by the consumer — used as the
                         correlation key for WS events and cancellation checks.
    conversation_id      PK of the ChatConversation.
    user_message_id      PK of the already-saved user ChatMessage.
    user_id              PK of the User — re-resolved from DB (safe for worker).
    workflow_id          Optional Workflow PK selected by the user.
    conversation_history Last ≤20 turns as [{"role", "content"}] — captured
                         before the user message was saved so this turn isn't
                         included twice.
    """
    from django.contrib.auth import get_user_model
    from django.core.cache import cache
    from chat.models import ChatConversation, ChatMessage
    from chat.notify import push_chat_chunk, push_chat_done, push_chat_error
    from chat.services import ChatService
    from chat.views import _save_output_attachments

    User = get_user_model()

    # acks_late means this exact call can be redelivered after a worker crash.
    # Claim the turn before doing anything else so a duplicate delivery is a
    # cheap no-op instead of a second assistant message.
    lock_key = f"chat_turn_lock_{turn_id}"
    if not cache.add(lock_key, 1, timeout=_HARD_LIMIT + 60):
        logger.info("run_chat_turn_task: turn %s already claimed — skipping duplicate delivery.", turn_id)
        return {"ok": True, "skipped": "duplicate_delivery", "turn_id": turn_id}

    def _cancelled() -> bool:
        from django.core.cache import cache
        return bool(cache.get(f"chat_cancel_{turn_id}"))

    def _clear_cancel():
        from django.core.cache import cache
        cache.delete(f"chat_cancel_{turn_id}")

    try:
        user = User.objects.get(pk=user_id)
        conv = ChatConversation.objects.get(pk=conversation_id, user=user)
        user_msg = ChatMessage.objects.get(pk=user_message_id)
        content  = user_msg.content

        from chat.models import Workflow
        workflow = None
        if workflow_id:
            workflow = Workflow.objects.filter(pk=workflow_id).first()

        # ── Run the agent ─────────────────────────────────────────────────────
        # ChatService.get_response already routes file + no-file paths through
        # the AI agent. We capture the full response text and output files here
        # then push them once complete.
        #
        # For true token-level streaming we would need to wire Grok's streaming
        # API into the ToolService loop — that's a future improvement. For now
        # we push the full response as a single chunk, which is still async
        # (the WS consumer returned immediately) and far better than blocking.

        if _cancelled():
            push_chat_error(conversation_id, message="Turn cancelled before starting.", turn_id=turn_id)
            _clear_cancel()
            return

        try:
            # Resolve any attachments saved on the user message so tools
            # invoked by the agent can access the saved file records.
            from chat.models import ChatMessageAttachment
            file_attachments = list(ChatMessageAttachment.objects.filter(message=user_msg))

            def _on_status_update(status, tool_name):
                from chat.notify import push_chat_status
                push_chat_status(conversation_id, status=status, tool_name=tool_name, turn_id=turn_id)

            response_text, output_files = ChatService.get_response(
                message=content,
                user=user,
                file_attachments=file_attachments,
                workflow_id=workflow_id,
                conversation_history=conversation_history or [],
                on_status_update=_on_status_update,
            )
        except SoftTimeLimitExceeded:
            push_chat_error(
                conversation_id,
                message="Processing took too long and was stopped. Try a smaller file.",
                turn_id=turn_id,
            )
            raise

        if _cancelled():
            _clear_cancel()
            push_chat_error(conversation_id, message="Turn cancelled.", turn_id=turn_id)
            return

        # ── Push text to WS ───────────────────────────────────────────────────
        # Send in chunks of 400 chars so the client can render progressively
        # without waiting for the full response.
        CHUNK = 400
        for i in range(0, len(response_text), CHUNK):
            push_chat_chunk(conversation_id, content=response_text[i:i + CHUNK], turn_id=turn_id)
            if _cancelled():
                _clear_cancel()
                push_chat_error(conversation_id, message="Turn cancelled mid-stream.", turn_id=turn_id)
                return

        # ── Save assistant message ────────────────────────────────────────────
        from chat.signals import mark_ws_origin, clear_ws_origin
        mark_ws_origin()
        try:
            assistant_msg = ChatMessage.objects.create(
                conversation=conv,
                role="assistant",
                content=response_text,
                applied_workflow=workflow,
            )
        finally:
            clear_ws_origin()

        # ── Persist output files ──────────────────────────────────────────────
        saved_attachments = _save_output_attachments(output_files, assistant_msg)
        attachment_meta = [
            {
                "id":       att.pk,
                "filename": att.filename,
                "file_type": att.file_type,
                "download_url": f"/api/chat/attachments/{att.pk}/download/",
            }
            for att in saved_attachments
        ]

        # ── Auto-title + bump updated_at ────────────────────────────────────────
        # updated_at must move on every turn, not just the title-generating
        # one — the sidebar sorts conversations by it (see chat-page.tsx's
        # restoreLastSession), and this task is now the only place a turn
        # runs regardless of entry point (WS or REST send), so it's the one
        # place this needs to happen.
        from django.utils import timezone
        if conv.title in ("Untitled Conversation", ""):
            from chat.title_generator import generate_title_from_user_input
            conv.title = generate_title_from_user_input(content) or content[:50]
        conv.updated_at = timezone.now()
        conv.save(update_fields=["title", "updated_at"])

        # ── Done ──────────────────────────────────────────────────────────────
        push_chat_done(
            conversation_id,
            message_id=assistant_msg.pk,
            turn_id=turn_id,
            attachments=attachment_meta,
        )

        _clear_cancel()
        logger.info(
            "chat turn %s complete: conv=%s user=%s",
            turn_id, conversation_id, user_id,
        )

        # Result payload for callers blocking on AsyncResult.get() — e.g. the
        # REST send views, which wait a bounded time for this so they can
        # return the same response shape as before instead of relying on the
        # WS push alone (see chat/views.py:_run_turn_via_worker).
        return {
            "ok": True,
            "turn_id": turn_id,
            "assistant_message_id": assistant_msg.pk,
            "attachment_ids": [a["id"] for a in attachment_meta],
        }

    except SoftTimeLimitExceeded:
        logger.error("run_chat_turn_task soft time limit exceeded: turn=%s", turn_id)
        raise
    except Exception as exc:
        logger.exception("run_chat_turn_task failed: turn=%s error=%s", turn_id, exc)
        from tools.services import is_transient_llm_error
        if is_transient_llm_error(exc) and self.request.retries < self.max_retries:
            # Release the lock so the retried delivery (a new task invocation,
            # not a redelivery of this one) isn't blocked by its own guard.
            cache.delete(lock_key)
            raise self.retry(exc=exc, countdown=15 * (self.request.retries + 1))
        push_chat_error(conversation_id, message=str(exc), turn_id=turn_id)
        raise