# Generated by Django 6.0.5 on 2026-08-24 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_id'),
        ('organizations', '0002_uuid_primary_key'),
    ]

    operations = [
    ]
