<<<<<<< HEAD
# Generated by Django 6.0.5 on 2026-08-28 09:57
=======
# Generated by Django 6.0.5 on 2026-08-27 13:16
>>>>>>> 9c5f81ebe29fbf4568f0a90898084aac81b2aa4b

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_merge_20260825_1132'),
        ('organizations', '0005_department'),
    ]

    operations = [
    ]
