# Generated by Django 6.0.5 on 2026-08-28 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_merge_0004_merge_20260825_1132_0005_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAPICredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_key', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('secret_hash', models.CharField(editable=False, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_credential', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization__name'],
            },
        ),
    ]
