# Generated by Django 6.0.5 on 2026-05-21 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('uploads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('workflow_type', models.CharField(choices=[('ura_processing', 'URA Fiscal Receipt Processing'), ('safaricom_processing', 'Safaricom Bill Processing'), ('acon_processing', 'ACON Sales Invoice Processing'), ('reconciliation', 'Reconciliation & Variance Detection'), ('classification', 'Line Item Classification'), ('report_generation', 'Report Generation'), ('custom', 'Custom Workflow')], max_length=30)),
                ('steps', models.JSONField(default=list, help_text="Ordered list of ToolDefinition.name values the AI should use, e.g. ['detect_file_type', 'extract_ura_receipts', 'generate_report'].")),
                ('system_prompt_prefix', models.TextField(blank=True, help_text="Extra instruction prepended to the system prompt when this workflow is selected, e.g. 'Focus on URA fiscal receipts only.'.")),
                ('enabled', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Show in the sidebar by default without the user needing to search.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'ordering': ['workflow_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Untitled Conversation', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_batch', models.ForeignKey(blank=True, help_text='Batch whose files provide context for this conversation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='uploads.uploadbatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Conversation',
                'verbose_name_plural': 'Chat Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_job', models.OneToOneField(blank=True, help_text='AI job that was created to fulfil this message, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_message', to='ai_engine.aianalysisjob')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatconversation')),
                ('applied_workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='chat.workflow')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat/attachments/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=20)),
                ('attachment_type', models.CharField(choices=[('user_upload', 'User Upload'), ('assistant_output', 'Assistant Output')], max_length=20)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.chatmessage')),
                ('uploaded_file', models.OneToOneField(blank=True, help_text='Corresponding UploadedFile record in the uploads pipeline.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_attachment', to='uploads.uploadedfile')),
            ],
            options={
                'verbose_name': 'Chat Message Attachment',
                'verbose_name_plural': 'Chat Message Attachments',
                'ordering': ['created_at'],
            },
        ),
    ]
