# Generated by Django 6.0.5 on 2026-08-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='workflow_type',
            field=models.CharField(choices=[('extraction', 'Document Extraction'), ('reconciliation', 'Reconciliation & Variance Detection'), ('anomaly_detection', 'Anomaly Detection'), ('data_cleaning', 'Data Cleaning'), ('batch_summary', 'Batch Summary'), ('report_generation', 'Report Generation'), ('classification', 'Line Item Classification'), ('ura_processing', 'URA Fiscal Receipt Processing'), ('safaricom_processing', 'Safaricom Bill Processing'), ('acon_processing', 'ACON Sales Invoice Processing'), ('full_pipeline', 'Full Pipeline'), ('custom', 'Custom Workflow')], max_length=30),
        ),
    ]
