# Generated by Django 6.0.5 on 2026-08-21 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_workflow_workflow_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatconversation',
            options={'ordering': ['-updated_at', '-pk'], 'verbose_name': 'Chat Conversation', 'verbose_name_plural': 'Chat Conversations'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at', 'pk'], 'verbose_name': 'Chat Message', 'verbose_name_plural': 'Chat Messages'},
        ),
    ]
