# Generated by Django 6.0.5 on 2026-08-23 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatconversation_options_and_more'),
        ('chat', '0003_uuid_primary_keys_and_attachment_paths'),
    ]

    operations = [
    ]
