# Generated by Django 6.0.5 on 2026-08-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_merge_20260825_1125'),
        ('chat', '0005_merge_20260825_1132'),
    ]

    operations = [
    ]
