# Generated by Django 6.0.5 on 2026-08-31 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_merge_20260827_1616'),
        ('chat', '0006_merge_20260828_1257'),
    ]

    operations = [
    ]
