# Generated by Django 6.0.5 on 2026-05-21 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Snake_case name exactly as sent to the LLM, e.g. 'extract_ura_receipts'.", max_length=80, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('description', models.TextField(help_text='Plain-English description the LLM reads to decide whether to call this tool. Be specific about what file types it accepts and what it returns.')),
                ('category', models.CharField(choices=[('extraction', 'Data Extraction'), ('transformation', 'Transformation'), ('reconciliation', 'Reconciliation'), ('analysis', 'AI Analysis'), ('report', 'Report Generation'), ('utility', 'Utility')], default='utility', max_length=20)),
                ('parameters_schema', models.JSONField(default=dict, help_text='JSON Schema describing the tool\'s input parameters. Example: {"type":"object","properties":{"file_id":{"type":"integer"}},"required":["file_id"]}')),
                ('handler', models.CharField(help_text='Dotted import path to the Python function that runs this tool.', max_length=200)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('is_safe', models.BooleanField(default=True, help_text='If False, requires explicit user confirmation before execution (e.g. tools that write to external systems).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tool Definition',
                'verbose_name_plural': 'Tool Definitions',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arguments', models.JSONField(default=dict, help_text="Arguments as parsed from the LLM's tool_call response.")),
                ('result', models.JSONField(blank=True, help_text='Serialisable return value from the handler function.', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='ai_engine.aianalysisjob')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calls', to='tools.tooldefinition')),
            ],
            options={
                'verbose_name': 'Tool Call',
                'verbose_name_plural': 'Tool Calls',
                'ordering': ['created_at'],
            },
        ),
    ]
