# Generated by Django 6.0.5 on 2026-08-05 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tooldefinition',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Null = system built-in; set = user-defined.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defined_tools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tooldefinition',
            name='tool_type',
            field=models.CharField(choices=[('builtin', 'Built-in Handler'), ('webhook', 'Webhook'), ('prompt_transform', 'Prompt Transform')], default='builtin', max_length=20),
        ),
        migrations.CreateModel(
            name='UserToolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_method', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET')], default='POST', max_length=10)),
                ('webhook_headers', models.JSONField(default=dict, help_text='Extra headers to send with the webhook request (e.g. auth tokens).')),
                ('webhook_timeout_seconds', models.PositiveSmallIntegerField(default=30)),
                ('system_prompt', models.TextField(blank=True, help_text="System prompt for prompt_transform tools. Use {file_text} as the placeholder for the uploaded file's content.")),
                ('output_schema', models.JSONField(blank=True, help_text='Optional JSON Schema the LLM output should conform to.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_config', to='tools.tooldefinition')),
            ],
        ),
    ]
