# Generated by Django 5.2.16 on 2026-08-13 10:20, hand-extended with a data backfill.

import django.db.models.deletion
from django.db import migrations, models


def backfill_tools_organization(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    ToolDefinition = apps.get_model("tools", "ToolDefinition")
    ToolCall = apps.get_model("tools", "ToolCall")

    default_org, _ = Organization.objects.get_or_create(
        slug="default", defaults={"name": "Default Organization"},
    )

    # Built-ins (created_by IS NULL) intentionally stay organization=None.
    for tool in ToolDefinition.objects.filter(organization__isnull=True, created_by__isnull=False).select_related("created_by"):
        tool.organization = tool.created_by.organization or default_org
        tool.save(update_fields=["organization"])

    for call in ToolCall.objects.filter(organization__isnull=True).select_related("job", "tool"):
        if call.job_id and call.job.organization_id:
            call.organization = call.job.organization
        elif call.tool_id and call.tool.organization_id:
            call.organization = call.tool.organization
        else:
            call.organization = default_org
        call.save(update_fields=["organization"])


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('tools', '0002_tooldefinition_created_by_tooldefinition_tool_type_and_more'),
        ('ai_engine', '0003_aianalysisjob_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolcall',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Denormalized at creation time — job may be null (standalone/test calls).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='tooldefinition',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Null for system built-ins. Set for user-defined tools — shared across the org.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='toolcall',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tooldefinition',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usertoolconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RunPython(backfill_tools_organization, migrations.RunPython.noop),
    ]
