# Generated by Django 6.0.5 on 2026-08-24 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_alter_toolcall_id_alter_tooldefinition_id_and_more'),
        ('tools', '0004_uuid_primary_keys'),
    ]

    operations = [
    ]
