# Generated by Django 6.0.5 on 2026-08-27 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_merge_20260825_1124'),
        ('tools', '0006_merge_20260825_1132'),
    ]

    operations = [
    ]
