# Generated by Django 6.0.5 on 2026-08-30 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_merge_20260828_1257'),
        ('uploads', '0009_merge_20260828_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolcall',
            name='uploaded_file',
            field=models.ForeignKey(blank=True, help_text='The file this tool was run against, when applicable (direct file-manager runs).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_calls', to='uploads.uploadedfile'),
        ),
    ]
