# Generated by Django 6.0.5 on 2026-08-31 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_merge_20260827_1616'),
        ('tools', '0008_toolcall_uploaded_file'),
    ]

    operations = [
    ]
