# Generated by Django 6.0.5 on 2026-05-21 19:03

import django.db.models.deletion
import uploads.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Human-readable name for this batch, e.g. 'April 2026 URA Receipts'.", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional notes about what this batch contains or why it was uploaded.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upload Batch',
                'verbose_name_plural': 'Upload Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=uploads.models._batch_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('extension', models.CharField(blank=True, help_text="Lowercased extension without dot, e.g. 'txt', 'pdf', 'xlsx'.", max_length=20)),
                ('detected_type', models.CharField(blank=True, help_text="AI-assigned document type, e.g. 'ura_fiscal_receipt', 'safaricom_bill', 'acon_export', 'unknown'.", max_length=60)),
                ('detection_confidence', models.CharField(blank=True, help_text="'high', 'medium', or 'low'.", max_length=10)),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('parse_error', 'Parse Error'), ('skipped', 'Skipped')], default='pending', max_length=15)),
                ('parse_error', models.TextField(blank=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, help_text='Plain-text representation of the file content used by the AI.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='uploads.uploadbatch')),
            ],
            options={
                'verbose_name': 'Uploaded File',
                'verbose_name_plural': 'Uploaded Files',
                'ordering': ['batch', 'uploaded_at'],
            },
        ),
    ]
