# Generated by Django 6.0.5 on 2026-07-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of pages in the document, if applicable.', null=True),
        ),
    ]
