# Generated by Django 6.0.5 on 2026-08-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_uploadedfile_page_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='extraction_deferred',
            field=models.BooleanField(default=False, help_text='True if text extraction was queued to a background worker.'),
        ),
    ]
