# Generated by Django 5.2.16 on 2026-08-13 10:10, hand-extended with a data backfill.

import django.db.models.deletion
from django.db import migrations, models


def backfill_batch_organization(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    UploadBatch = apps.get_model("uploads", "UploadBatch")

    default_org, _ = Organization.objects.get_or_create(
        slug="default", defaults={"name": "Default Organization"},
    )
    for batch in UploadBatch.objects.filter(organization__isnull=True).select_related("uploaded_by"):
        batch.organization = (
            batch.uploaded_by.organization if batch.uploaded_by_id and batch.uploaded_by.organization_id
            else default_org
        )
        batch.save(update_fields=["organization"])


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('users', '0006_organization_backfill'),
        ('uploads', '0003_uploadedfile_extraction_deferred'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.organization'),
        ),
        migrations.RunPython(backfill_batch_organization, migrations.RunPython.noop),
    ]
