# Generated by Django 6.0.5 on 2026-08-21 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_uploadbatch_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('file.received', 'File received'), ('file.stored', 'File stored'), ('file.queued', 'Extraction queued'), ('file.extracting', 'Extraction in progress'), ('file.parsed', 'Extraction complete'), ('file.parse_error', 'Extraction failed'), ('file.detected', 'Type detected'), ('batch.progress', 'Batch counters updated'), ('batch.completed', 'Batch finished')], max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='uploads.uploadbatch')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='uploads.uploadedfile')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['batch', 'created_at'], name='uploads_pip_batch_i_f3e75a_idx')],
            },
        ),
    ]
