# Generated by Django 6.0.5 on 2026-08-23 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_pipelineevent'),
        ('uploads', '0005_uuid_primary_keys_and_file_paths'),
    ]

    operations = [
    ]
