# Generated by Django 6.0.5 on 2026-08-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_merge_20260823_2311'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pipelineevent',
            name='uploads_pip_batch_i_f3e75a_idx',
        ),
        migrations.DeleteModel(
            name='PipelineEvent',
        ),
    ]
