# Generated by Django 6.0.5 on 2026-08-25 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_merge_20260823_2311'),
        ('uploads', '0006_merge_20260824_0827'),
    ]

    operations = [
    ]
