# Generated by Django 6.0.5 on 2026-08-28 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0007_merge_20260825_1125'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pipelineevent',
            name='uploads_pip_batch_i_f3e75a_idx',
        ),
        migrations.DeleteModel(
            name='PipelineEvent',
        ),
    ]
