# Generated by Django 6.0.5 on 2026-08-26 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0007_merge_20260825_1132'),
        ('uploads', '0007_remove_pipelineevent_uploads_pip_batch_i_f3e75a_idx_and_more'),
    ]

    operations = [
    ]
