# Generated by Django 6.0.5 on 2026-08-28 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0007_merge_20260825_1125'),
    ]

    # No-op: this duplicated 0007_remove_pipelineevent_..._and_more's
    # RemoveIndex/DeleteModel on a divergent branch. That branch was later
    # merged in via 0008_merge_20260826_1044, which already applies the same
    # deletion — replaying it a second time here broke migration state
    # construction with KeyError('uploads', 'pipelineevent') once both
    # branches were merged. Kept as a dependency placeholder only.
    operations = [
    ]
