# Generated by Django 6.0.5 on 2026-08-28 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0007_merge_20260825_1125'),
        ('uploads', '0008_merge_20260826_1044'),
    ]

    operations = [
    ]
