# Generated by Django 6.0.5 on 2026-08-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0008_merge_20260826_1044'),
        ('uploads', '0008_remove_pipelineevent_uploads_pip_batch_i_f3e75a_idx_and_more'),
    ]

    operations = [
    ]
